---
name: Create and publish a libvirt image

permissions:
  actions: read
  contents: read
  id-token: write
  packages: write
  pull-requests: write
  security-events: write

on:
  pull_request:
    paths:
      - .github/workflows/container-build-libvirt.yaml
      - ContainerFiles/libvirt
  schedule:
    - cron: '0 0 * * 0'  # Run Weekly at midnight UTC
  workflow_dispatch:
    inputs:
      ovs-tag:
        description: 'Version of ovs to merge into image'
        required: true
        default: "v3.5.2-3.13-trixie-latest"
        type: choice
        options:
          - v3.5.2-3.13-trixie-latest
          - v3.5.2-3.12-bookworm-latest
      libguestfs-tag:
        description: 'Version of libguestfs to merge into image'
        required: true
        default: "v1.56.2-3.13-trixie-latest"
        type: choice
        options:
          - v1.56.2-3.13-trixie-latest
          - v1.56.2-3.12-bookworm-latest
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/libvirt
  ovs_tag: >
    ['v3.5.2-3.13-trixie-latest','v3.5.2-3.12-bookworm-latest']
  libguestfs_tag: >
    ['v1.56.2-3.13-trixie-latest','v1.56.2-3.12-bookworm-latest']
jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      ovs-tag: ${{ steps.generate-matrix.outputs.ovs_tag }}
      libguestfs-tag: ${{ steps.generate-matrix.outputs.libguestfs_tag }}
    steps:
      - name: generate-matrix
        id: generate-matrix
        run: |
          if [ "${{ github.event_name == 'workflow_dispatch' }}" = "true" ]; then
            ovs_tag="$(echo '${{ github.event.inputs.ovs-tag }}' | jq -R '[select(length>0)]' | jq -c '.')"
            libguestfs_tag="$(echo '${{ github.event.inputs.libguestfs-tag }}' | jq -R '[select(length>0)]' | jq -c '.')"
          fi
          echo "ovs_tag=${ovs_tag:-${{ env.ovs_tag }}}" >> $GITHUB_OUTPUT
          echo "libguestfs_tag=${libguestfs_tag:-${{ env.libguestfs_tag }}}" >> $GITHUB_OUTPUT

  build-and-push-image:
    needs:
      - init
    strategy:
      matrix:
        ovs-tag: ${{ fromJSON(needs.init.outputs.ovs-tag) }}
        libguestfs-tag: ${{ fromJSON(needs.init.outputs.libguestfs-tag) }}
        exclude:
          - ovs-tag: v3.5.2-3.13-trixie-latest
            libguestfs-tag: v1.56.2-3.12-bookworm-latest
          - ovs-tag: v3.5.2-3.12-bookworm-latest
            libguestfs-tag: v1.56.2-3.13-trixie-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Dynamically set MY_DATE, NAME environment variable
        run: |
          echo "MY_DATE=$(date +%s)" >> $GITHUB_ENV

          NAME=$(echo -n "${{ env.IMAGE_NAME }}" | awk -F'/' '{print $NF}')
          echo "CATEGORY_NAME=${VERSION}-${NAME}" >> $GITHUB_ENV
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Set registry URL
        run: |
          echo "GHCR_URL=${REGISTRY}/${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      - name: Dynamically set MY_DATE environment variable
        run: echo "MY_DATE=$(date +%s)" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ContainerFiles/libvirt
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.IMAGE_NAME }}:local
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CACHEBUST=${{ github.sha }}
            GHCR_URL=${{ env.GHCR_URL }}
            OVS_TAG=${{ matrix.ovs-tag }}
            LIBGUESTFS_TAG=${{ matrix.libguestfs-tag }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1  # using latest trivy scanner
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
        with:
          image-ref: '${{ env.IMAGE_NAME }}:local'
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        continue-on-error: true
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          category: "${{ env.CATEGORY_NAME }}"
      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@0.33.1  # using latest trivy scanner
        if: ${{ github.event_name == 'pull_request' }}
        with:
          image-ref: '${{ env.IMAGE_NAME }}:local'
          output: trivy.txt
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
      - name: Create trivy output file in markdown format
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [[ -s trivy.txt ]]; then
              echo "### Security Output" > trivy-output.txt
              echo '```terraform' >> trivy-output.txt
              cat trivy.txt >> trivy-output.txt
              echo '```' >> trivy-output.txt
          fi
      - name: Publish Trivy Output to Summary
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          if [[ -s trivy-output.txt ]]; then
            {
              cat trivy-output.txt
            } >> $GITHUB_STEP_SUMMARY
          fi
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ContainerFiles/libvirt
          push: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.libguestfs-tag }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.MY_DATE }}-${{ matrix.libguestfs-tag }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.MY_DATE }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CACHEBUST=${{ github.sha }}
            GHCR_URL=${{ env.GHCR_URL }}
            OVS_TAG=${{ matrix.ovs-tag }}
            LIBGUESTFS_TAG=${{ matrix.libguestfs-tag }}
